# Generated by Django 3.2.5 on 2022-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_phone_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
