# Generated by Django 3.2.5 on 2022-04-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_member_info_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
