# Generated by Django 3.2.5 on 2022-04-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_member_info_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Profile_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='member_info',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
