# Generated by Django 3.2.5 on 2022-04-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20220408_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
