# Generated by Django 3.2.5 on 2022-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_member_info_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_donation',
            name='added_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
