# Generated by Django 3.2.5 on 2022-04-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_member_donation_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_donation',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
