# Generated by Django 3.2.5 on 2022-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20220415_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_donation',
            name='account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
